# Generated by Django 4.2.23 on 2025-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationprofile",
            name="tid",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="단말기 번호"
            ),
        ),
    ]
