# Generated by Django 4.2.7 on 2025-07-02 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(max_length=100, verbose_name="주유소명"),
                ),
                (
                    "station_address",
                    models.CharField(max_length=200, verbose_name="주유소 주소"),
                ),
                (
                    "business_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="사업자 번호"
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=50, verbose_name="대표자명"),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="운영시간"
                    ),
                ),
                (
                    "services",
                    models.TextField(blank=True, null=True, verbose_name="제공 서비스"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="위도",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="경도",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="승인 여부"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="승인일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "주유소 프로필",
                "verbose_name_plural": "주유소 프로필들",
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="차량 번호"
                    ),
                ),
                (
                    "car_model",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="차량 모델"
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GASOLINE", "휘발유"),
                            ("DIESEL", "경유"),
                            ("LPG", "LPG"),
                            ("ELECTRIC", "전기"),
                            ("HYBRID", "하이브리드"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="연료 타입",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "고객 프로필",
                "verbose_name_plural": "고객 프로필들",
            },
        ),
    ]
