# Generated by Django 4.2.7 on 2025-07-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0002_stationprofile_customerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pw_back",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="백업 패스워드"
            ),
        ),
    ]
