# Generated by Django 4.2.23 on 2025-07-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0003_remove_stationprofile_station_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stationprofile",
            options={
                "verbose_name": "주유소 프로필",
                "verbose_name_plural": "5. 주유소 프로필들",
            },
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="last_fuel_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="최근 주유량(L)",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="last_fuel_date",
            field=models.DateField(blank=True, null=True, verbose_name="최근 주유일"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="monthly_fuel_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="월 주유량(L)"
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="total_fuel_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="총 주유량(L)"
            ),
        ),
    ]
