# Generated by Django 4.2.7 on 2025-07-02 05:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0003_customuser_pw_back"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerUser",
            fields=[],
            options={
                "verbose_name": "일반 고객",
                "verbose_name_plural": "2. 일반 고객들",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Cust_User.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="StationUser",
            fields=[],
            options={
                "verbose_name": "주유소 고객들",
                "verbose_name_plural": "3. 주유소 고객들",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Cust_User.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="customerprofile",
            options={
                "verbose_name": "고객 프로필",
                "verbose_name_plural": "4. 고객 프로필들",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "사용자", "verbose_name_plural": "1. 사용자들"},
        ),
        migrations.AlterModelOptions(
            name="stationprofile",
            options={
                "verbose_name": "주유소 프로필",
                "verbose_name_plural": "5. 주유소 프로필들",
            },
        ),
        migrations.CreateModel(
            name="CustomerStationRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주 거래처 여부"),
                ),
                (
                    "registration_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "last_visit_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="최근 방문일"
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True, verbose_name="메모")),
                (
                    "points",
                    models.PositiveIntegerField(default=0, verbose_name="적립 포인트"),
                ),
                (
                    "visit_count",
                    models.PositiveIntegerField(default=0, verbose_name="방문 횟수"),
                ),
                (
                    "preferred_fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GASOLINE", "휘발유"),
                            ("DIESEL", "경유"),
                            ("LPG", "LPG"),
                            ("ELECTRIC", "전기"),
                            ("HYBRID", "하이브리드"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="선호 유종",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "CUSTOMER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_stations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="고객",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_customers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객-주유소 관계",
                "verbose_name_plural": "6. 고객-주유소 관계",
                "ordering": ["-registration_date"],
                "unique_together": {("customer", "station")},
            },
        ),
    ]
