# Generated by Django 4.2.7 on 2025-07-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0004_customeruser_stationuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="이름"
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="전화번호"
            ),
        ),
    ]
