# Generated by Django 4.2.7 on 2025-07-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0005_customerprofile_name_customerprofile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="customer_phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="고객 전화번호"
            ),
        ),
        migrations.AddField(
            model_name="stationprofile",
            name="station_phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="주유소 전화번호"
            ),
        ),
    ]
