# Generated by Django 4.2.23 on 2025-07-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0005_customerprofile_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="주유소 위도 좌표",
                max_digits=9,
                null=True,
                verbose_name="위도",
            ),
        ),
        migrations.AddField(
            model_name="stationprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="주유소 경도 좌표",
                max_digits=9,
                null=True,
                verbose_name="경도",
            ),
        ),
    ]
