# Generated by Django 4.2.7 on 2025-07-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0006_remove_customerprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="bonus_card",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="보너스카드 번호"
            ),
        ),
    ]
