# Generated by Django 4.2.7 on 2025-07-03 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0007_customerprofile_bonus_card"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stationprofile",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="stationprofile",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="stationprofile",
            name="opening_hours",
        ),
        migrations.RemoveField(
            model_name="stationprofile",
            name="services",
        ),
    ]
