# Generated by Django 4.2.7 on 2025-07-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0008_remove_stationprofile_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="point_card_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="포인트카드 번호",
            ),
        ),
    ]
