# Generated by Django 4.2.7 on 2025-07-04 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0009_customuser_point_card_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="point_card_number",
        ),
    ]
