# Generated by Django 4.2.23 on 2025-07-07 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cust_StationApp', '0005_stationlist'),
        ('Cust_User', '0010_remove_customuser_point_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_point', models.IntegerField(default=0, verbose_name='현재 포인트')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='마지막 사용일')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_points', to=settings.AUTH_USER_MODEL, verbose_name='고객')),
                ('point_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_points', to='Cust_StationApp.pointcard', verbose_name='포인트 카드')),
            ],
            options={
                'verbose_name': '고객 포인트 카드',
                'verbose_name_plural': '고객 포인트 카드들',
                'ordering': ['-updated_at'],
                'unique_together': {('customer', 'point_card')},
            },
        ),
        migrations.CreateModel(
            name='FuelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('GASOLINE', '휘발유'), ('DIESEL', '경유'), ('LPG', 'LPG'), ('PREMIUM', '고급 휘발유')], max_length=10, verbose_name='유종')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='주유량(L)')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='리터당 가격')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 금액')),
                ('earned_points', models.IntegerField(default=0, verbose_name='적립 포인트')),
                ('used_points', models.IntegerField(default=0, verbose_name='사용 포인트')),
                ('fueled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='주유 일시')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_histories', to=settings.AUTH_USER_MODEL, verbose_name='주유소')),
                ('station_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_histories', to='Cust_User.stationpoint', verbose_name='포인트 카드')),
            ],
            options={
                'verbose_name': '주유 이력',
                'verbose_name_plural': '주유 이력들',
                'ordering': ['-fueled_at'],
            },
        ),
    ]
