# Generated by Django 4.2.23 on 2025-07-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cust_User', '0011_stationpoint_fuelhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationpoint',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stationpoint',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='stationpoint',
            name='point_card',
        ),
        migrations.RemoveField(
            model_name='customerstationrelation',
            name='points',
        ),
        migrations.DeleteModel(
            name='FuelHistory',
        ),
        migrations.DeleteModel(
            name='StationPoint',
        ),
    ]
