# Generated by Django 4.2.23 on 2025-07-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0012_alter_stationpoint_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stationprofile",
            options={
                "verbose_name": "주유소 프로필",
                "verbose_name_plural": "주유소 프로필",
            },
        ),
        migrations.RemoveField(
            model_name="stationprofile",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="stationprofile",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="stationprofile",
            name="owner_name",
        ),
        migrations.RemoveField(
            model_name="stationprofile",
            name="station_address",
        ),
        migrations.RemoveField(
            model_name="stationprofile",
            name="station_phone",
        ),
        migrations.AddField(
            model_name="stationprofile",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="주소"
            ),
        ),
        migrations.AddField(
            model_name="stationprofile",
            name="agency_code",
            field=models.CharField(
                default="000", max_length=3, verbose_name="대리점코드"
            ),
        ),
        migrations.AddField(
            model_name="stationprofile",
            name="oil_company_code",
            field=models.CharField(
                default="0", max_length=1, verbose_name="정유사코드"
            ),
        ),
        migrations.AddField(
            model_name="stationprofile",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="전화번호"
            ),
        ),
        migrations.AddField(
            model_name="stationprofile",
            name="station_code",
            field=models.CharField(
                default="000000000000", max_length=12, verbose_name="주유소코드"
            ),
        ),
        migrations.AlterField(
            model_name="stationprofile",
            name="business_number",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="사업자등록번호"
            ),
        ),
    ]
