# Generated by Django 4.2.23 on 2025-07-08 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0013_update_station_profile_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerstationrelation",
            options={
                "verbose_name": "고객-주유소 관계",
                "verbose_name_plural": "고객-주유소 관계",
            },
        ),
        migrations.RenameField(
            model_name="customerstationrelation",
            old_name="registration_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="customerstationrelation",
            name="last_visit_date",
        ),
        migrations.RemoveField(
            model_name="customerstationrelation",
            name="memo",
        ),
        migrations.RemoveField(
            model_name="customerstationrelation",
            name="preferred_fuel_type",
        ),
        migrations.RemoveField(
            model_name="customerstationrelation",
            name="visit_count",
        ),
        migrations.AddField(
            model_name="customerstationrelation",
            name="points",
            field=models.PositiveIntegerField(default=0, verbose_name="포인트"),
        ),
        migrations.AddField(
            model_name="customerstationrelation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="customerstationrelation",
            name="customer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "CUSTOMER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station_relations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="고객",
            ),
        ),
        migrations.AlterField(
            model_name="customerstationrelation",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="주거래 여부"),
        ),
        migrations.AlterField(
            model_name="customerstationrelation",
            name="station",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "STATION"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_relations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="주유소",
            ),
        ),
    ]
