# Generated by Django 4.2.23 on 2025-07-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0014_alter_customerstationrelation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerstationrelation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성화 여부"),
        ),
    ]
