# Generated by Django 4.2.23 on 2025-07-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0015_customerstationrelation_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="bonus_card",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
