# Generated by Django 4.2.23 on 2025-07-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0016_alter_customerprofile_bonus_card_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="bonus_card",
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="membership_card",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="멤버십 카드 번호"
            ),
        ),
    ]
