# Generated by Django 4.2.23 on 2025-07-09 14:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("OilNote_User", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PointCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="카드번호"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="사용 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="등록일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "tids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="주유소 TID 목록"
                    ),
                ),
            ],
            options={
                "verbose_name": "멤버쉽카드",
                "verbose_name_plural": "멤버쉽카드",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StationList",
            fields=[],
            options={
                "verbose_name": "주유소",
                "verbose_name_plural": "주유소 목록",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OilNote_User.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="StationCardMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="등록일"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "tid",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="주유소 TID"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="OilNote_StationApp.pointcard",
                        verbose_name="포인트카드",
                    ),
                ),
            ],
            options={
                "verbose_name": "주유소-카드 매핑",
                "verbose_name_plural": "주유소-카드 매핑",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="PointHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="포인트 변경")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("적립", "적립"),
                            ("사용", "사용"),
                            ("수정", "수정"),
                            ("차감", "차감"),
                        ],
                        max_length=10,
                        verbose_name="변경 유형",
                    ),
                ),
                ("reason", models.CharField(max_length=200, verbose_name="변경 사유")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "customer_station_relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_history",
                        to="OilNote_User.customerstationrelation",
                        verbose_name="고객-주유소 관계",
                    ),
                ),
            ],
            options={
                "verbose_name": "포인트 내역",
                "verbose_name_plural": "포인트 내역",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file_name", models.CharField(max_length=255)),
                ("original_file_name", models.CharField(max_length=255)),
                ("sales_date", models.DateField()),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sales_date"],
                "unique_together": {("station", "sales_date")},
            },
        ),
    ]
