# Generated by Django 4.2.23 on 2025-07-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "OilNote_StationApp",
            "0002_alter_pointcard_options_alter_pointcard_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pointcard",
            name="agency_code",
            field=models.CharField(
                default="000",
                help_text="대리점 코드 (3자리)",
                max_length=3,
                verbose_name="대리점코드",
            ),
        ),
        migrations.AddField(
            model_name="pointcard",
            name="oil_company_code",
            field=models.CharField(
                default="0",
                help_text="정유사 코드 (1자리)",
                max_length=1,
                verbose_name="정유사코드",
            ),
        ),
    ]
