# Generated by Django 4.2.23 on 2025-07-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_StationApp", "0003_pointcard_agency_code_pointcard_oil_company_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PointHistory",
        ),
    ]
