# Generated by Django 4.2.23 on 2025-07-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_StationApp", "0004_delete_pointhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelSalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blank_column",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="공백"
                    ),
                ),
                ("sale_date", models.DateField(verbose_name="판매일자")),
                ("sale_time", models.TimeField(verbose_name="주유시간")),
                (
                    "customer_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="고객번호"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="고객명"
                    ),
                ),
                (
                    "issue_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="발행번호"
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="주류상품종류",
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="판매구분"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="결제구분"
                    ),
                ),
                (
                    "sale_type2",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="판매구분2"
                    ),
                ),
                (
                    "nozzle",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="노즐"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="제품코드"
                    ),
                ),
                (
                    "product_pack",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="제품/PACK"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="판매수량",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="판매단가",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="판매금액",
                    ),
                ),
                (
                    "earned_points",
                    models.IntegerField(default=0, verbose_name="적립포인트"),
                ),
                ("points", models.IntegerField(default=0, verbose_name="포인트")),
                ("bonus", models.IntegerField(default=0, verbose_name="보너스")),
                (
                    "pos_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="POS_ID"
                    ),
                ),
                (
                    "pos_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="POS코드"
                    ),
                ),
                (
                    "store",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="판매점"
                    ),
                ),
                (
                    "receipt",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="영수증"
                    ),
                ),
                (
                    "approval_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="승인번호"
                    ),
                ),
                (
                    "approval_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="승인일시"
                    ),
                ),
                (
                    "bonus_card",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="보너스카드"
                    ),
                ),
                (
                    "customer_card_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="고객카드번호",
                    ),
                ),
                (
                    "data_created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="데이터생성일시"
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="원본 파일명",
                    ),
                ),
            ],
            options={
                "verbose_name": "엑셀 매출 데이터",
                "verbose_name_plural": "엑셀 매출 데이터 목록",
                "ordering": ["-sale_date", "-sale_time"],
            },
        ),
    ]
