# Generated by Django 4.2.23 on 2025-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_StationApp", "0005_excelsalesdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelsalesdata",
            name="tid",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="주유소 TID"
            ),
        ),
    ]
