# Generated by Django 4.2.23 on 2025-07-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_StationApp", "0007_salesstatistics"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="excelsalesdata",
            options={
                "ordering": ["-sale_date", "-sale_time"],
                "verbose_name": "엑셀 매출 데이터",
                "verbose_name_plural": "5. 엑셀 매출 데이터 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="pointcard",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "멤버십 카드",
                "verbose_name_plural": "1. 멤버십 카드 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="salesstatistics",
            options={
                "ordering": ["-sale_date", "-created_at"],
                "verbose_name": "매출 통계",
                "verbose_name_plural": "4. 매출 통계 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="stationlist",
            options={"verbose_name": "주유소", "verbose_name_plural": "2. 주유소 목록"},
        ),
        migrations.AlterUniqueTogether(
            name="salesstatistics",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="salesstatistics",
            name="tid",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="주유소 TID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesstatistics",
            unique_together={("tid", "sale_date")},
        ),
    ]
