# Generated by Django 4.2.23 on 2025-07-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "OilNote_StationApp",
            "0008_alter_excelsalesdata_options_alter_pointcard_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlySalesStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tid",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="주유소 TID"
                    ),
                ),
                (
                    "year_month",
                    models.CharField(max_length=7, verbose_name="년월 (YYYY-MM)"),
                ),
                (
                    "total_transactions",
                    models.IntegerField(default=0, verbose_name="총 거래건수"),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="총 판매수량",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="총 판매금액",
                    ),
                ),
                (
                    "avg_unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="평균 단가",
                    ),
                ),
                (
                    "top_product",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="최다 판매 제품",
                    ),
                ),
                (
                    "top_product_count",
                    models.IntegerField(default=0, verbose_name="최다 판매 제품 수량"),
                ),
                (
                    "product_breakdown",
                    models.JSONField(default=dict, verbose_name="유종별 판매 현황"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="업데이트일시"),
                ),
            ],
            options={
                "verbose_name": "월별 매출 통계",
                "verbose_name_plural": "6. 월별 매출 통계 목록",
                "ordering": ["-year_month"],
                "unique_together": {("tid", "year_month")},
            },
        ),
    ]
