# Generated by Django 4.2.23 on 2025-07-18 10:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OilNote_StationApp", "0011_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneCardMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="하이픈(-) 없이 숫자만 입력 (예: 01012345678)",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="올바른 휴대폰 번호를 입력해주세요. (예: 01012345678)",
                                regex="^01[0-9]{8,9}$",
                            )
                        ],
                        verbose_name="전화번호",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="고객이 회원가입하여 연동되었는지 여부",
                        verbose_name="사용 여부",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "linked_user",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "CUSTOMER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_card_mappings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="연동된 사용자",
                    ),
                ),
                (
                    "membership_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_mappings",
                        to="OilNote_StationApp.pointcard",
                        verbose_name="멤버십 카드",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록 주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "폰번호-카드 연동",
                "verbose_name_plural": "3. 폰번호-카드 연동 목록",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number"], name="Cust_Statio_phone_n_7856c7_idx"
                    ),
                    models.Index(
                        fields=["membership_card"],
                        name="Cust_Statio_members_258070_idx",
                    ),
                    models.Index(
                        fields=["is_used"], name="Cust_Statio_is_used_cf786c_idx"
                    ),
                ],
                "unique_together": {("phone_number", "station")},
            },
        ),
    ]
