# Generated by Django 4.2.23 on 2025-07-21 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OilNote_StationApp", "0014_coupon"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_name",
                    models.CharField(
                        help_text="고객에게 표시될 쿠폰 이름",
                        max_length=100,
                        verbose_name="쿠폰명",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="쿠폰에 대한 상세 설명",
                        null=True,
                        verbose_name="설명",
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("DISCOUNT", "할인"),
                            ("PRODUCT", "상품"),
                            ("BOTH", "할인+상품"),
                        ],
                        max_length=10,
                        verbose_name="혜택 유형",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="정액 할인 금액 (원)",
                        max_digits=10,
                        verbose_name="할인 금액",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="무료 제공할 상품명",
                        max_length=100,
                        null=True,
                        verbose_name="상품명",
                    ),
                ),
                (
                    "is_permanent",
                    models.BooleanField(default=False, verbose_name="무기한 여부"),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="사용 시작일"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="사용 종료일"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "쿠폰 템플릿",
                "verbose_name_plural": "9. 쿠폰 템플릿 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        help_text="기본 유형(SIGNUP, CARWASH, PRODUCT, FUEL) 또는 사용자 정의 코드",
                        max_length=20,
                        verbose_name="유형 코드",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        help_text="쿠폰 유형의 표시명",
                        max_length=50,
                        verbose_name="유형명",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="기본 4개 유형인지 사용자 정의 유형인지 구분",
                        verbose_name="기본 유형 여부",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "station",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "쿠폰 유형",
                "verbose_name_plural": "8. 쿠폰 유형 목록",
                "ordering": ["is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "사용가능"),
                            ("USED", "사용완료"),
                            ("EXPIRED", "만료됨"),
                        ],
                        default="AVAILABLE",
                        max_length=10,
                        verbose_name="사용 상태",
                    ),
                ),
                (
                    "issued_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="발행일시"),
                ),
                (
                    "used_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="사용일시"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="만료일"),
                ),
                (
                    "used_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="쿠폰 사용 시 거래 금액",
                        max_digits=10,
                        null=True,
                        verbose_name="사용 금액",
                    ),
                ),
                (
                    "coupon_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OilNote_StationApp.coupontemplate",
                        verbose_name="쿠폰 템플릿",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "CUSTOMER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="고객",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객 쿠폰",
                "verbose_name_plural": "10. 고객 쿠폰 목록",
                "ordering": ["-issued_date"],
            },
        ),
        migrations.DeleteModel(
            name="Coupon",
        ),
        migrations.AddField(
            model_name="coupontemplate",
            name="coupon_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="OilNote_StationApp.coupontype",
                verbose_name="쿠폰 유형",
            ),
        ),
        migrations.AddField(
            model_name="coupontemplate",
            name="station",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "STATION"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="주유소",
            ),
        ),
        migrations.AddIndex(
            model_name="customercoupon",
            index=models.Index(
                fields=["customer", "status"], name="Cust_Statio_custome_0073a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customercoupon",
            index=models.Index(
                fields=["coupon_template"], name="Cust_Statio_coupon__43b3f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coupontype",
            unique_together={("station", "type_code")},
        ),
    ]
