# Generated by Django 4.2.23 on 2025-07-21 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OilNote_StationApp", "0015_coupontemplate_coupontype_customercoupon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationcardmapping",
            name="station",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "STATION"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_mappings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="주유소",
            ),
        ),
    ]
