# Generated by Django 4.2.23 on 2025-07-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_StationApp", "0016_stationcardmapping_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonecardmapping",
            name="car_number",
            field=models.CharField(
                blank=True,
                help_text="고객의 차량 번호 (선택사항)",
                max_length=20,
                null=True,
                verbose_name="차량 번호",
            ),
        ),
    ]
