# Generated by Django 4.2.23 on 2025-07-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_StationApp", "0021_auto_20250724_1502"),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocoupontemplate',
            name='benefit_type',
            field=models.CharField(
                choices=[('DISCOUNT', '할인'), ('PRODUCT', '상품'), ('BOTH', '할인+상품')], 
                max_length=10, 
                verbose_name='혜택 유형'
            ),
        ),
    ]
