# Generated by Django 4.2.23 on 2025-07-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_StationApp", "0027_remove_issue_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelsalesdata",
            name="is_cumulative_processed",
            field=models.BooleanField(
                default=False,
                help_text="누적매출 추적 처리 여부",
                verbose_name="누적매출 처리 완료",
            ),
        ),
    ]
