# Generated by Django 4.2.23 on 2025-08-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_StationApp", "0029_add_max_issue_count"),
    ]

    operations = [
        # RemoveIndex 작업 제거 - 존재하지 않는 인덱스
        # migrations.RemoveIndex(
        #     model_name="autocoupontemplate",
        #     name="Cust_Statio_priorit_554c66_idx",
        # ),
        # migrations.RemoveIndex(
        #     model_name="cumulativesalestracker",
        #     name="Cust_Station_cumulative_idx",
        # ),
        # 모든 RenameIndex 작업 주석 처리 - 존재하지 않는 인덱스 문제
        # migrations.RenameIndex(
        #     model_name="autocoupontemplate",
        #     new_name="OilNote_Sta_station_282eb8_idx",
        #     old_name="Cust_Statio_station_f477f1_idx",
        # ),
        # migrations.RenameIndex(
        #     model_name="autocoupontemplate",
        #     new_name="OilNote_Sta_station_282eb8_idx",
        #     old_name="Cust_Station_auto_coupon_idx",
        # ),
        # migrations.RenameIndex(
        #     model_name="customercoupon",
        #     new_name="OilNote_Sta_custome_3770fe_idx",
        #     old_name="Cust_Statio_custome_0073a4_idx",
        # ),
        # migrations.RenameIndex(
        #     model_name="customercoupon",
        #     new_name="OilNote_Sta_coupon__f90d2e_idx",
        #     old_name="Cust_Statio_coupon__43b3f4_idx",
        # ),
        # migrations.RenameIndex(
        #     model_name="customercoupon",
        #     new_name="OilNote_Sta_auto_co_0221ca_idx",
        #     old_name="Cust_Statio_auto_co_180c3b_idx",
        # ),
        # migrations.RenameIndex(
        #     model_name="phonecardmapping",
        #     new_name="OilNote_Sta_phone_n_252a02_idx",
        #     old_name="Cust_Statio_phone_n_7856c7_idx",
        # ),
        # migrations.RenameIndex(
        #     model_name="phonecardmapping",
        #     new_name="OilNote_Sta_members_9814ea_idx",
        #     old_name="Cust_Statio_members_258070_idx",
        # ),
        # migrations.RenameIndex(
        #     model_name="phonecardmapping",
        #     new_name="OilNote_Sta_is_used_aad4c0_idx",
        #     old_name="Cust_Statio_is_used_cf786c_idx",
        # ),
        # 존재하지 않는 필드 문제로 주석 처리
        # migrations.AlterUniqueTogether(
        #     name="autocoupontemplate",
        #     unique_together=set(),
        # ),
        migrations.AlterField(
            model_name="autocouponcondition",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("THRESHOLD_AMOUNT", "금액 임계값"),
                    ("TIME_PERIOD", "기간 조건"),
                    ("CUSTOMER_TYPE", "고객 유형"),
                    ("EXCLUDE_PREVIOUS", "기존 수령자 제외"),
                    ("VISIT_COUNT", "방문 횟수"),
                    ("WEEKDAY_ONLY", "평일만"),
                    ("WEEKEND_ONLY", "주말만"),
                    ("CUSTOMER_GRADE", "고객 등급"),
                ],
                max_length=20,
                verbose_name="조건 유형",
            ),
        ),
        migrations.AlterModelTable(
            name="autocouponcondition",
            table="OilNote_StationApp_autocouponcondition",
        ),
        migrations.AlterModelTable(
            name="autocoupontemplate",
            table="OilNote_StationApp_autocoupontemplate",
        ),
        migrations.AlterModelTable(
            name="couponpurchaserequest",
            table="OilNote_StationApp_couponpurchaserequest",
        ),
        migrations.AlterModelTable(
            name="coupontemplate",
            table="OilNote_StationApp_coupontemplate",
        ),
        migrations.AlterModelTable(
            name="coupontype",
            table="OilNote_StationApp_coupontype",
        ),
        migrations.AlterModelTable(
            name="cumulativesalestracker",
            table="OilNote_StationApp_cumulativesalestracker",
        ),
        migrations.AlterModelTable(
            name="customercoupon",
            table="OilNote_StationApp_customercoupon",
        ),
        migrations.AlterModelTable(
            name="excelsalesdata",
            table="OilNote_StationApp_excelsalesdata",
        ),
        migrations.AlterModelTable(
            name="group",
            table="OilNote_StationApp_group",
        ),
        migrations.AlterModelTable(
            name="monthlysalesstatistics",
            table="OilNote_StationApp_monthlysalesstatistics",
        ),
        migrations.AlterModelTable(
            name="phonecardmapping",
            table="OilNote_StationApp_phonecardmapping",
        ),
        migrations.AlterModelTable(
            name="pointcard",
            table="OilNote_StationApp_pointcard",
        ),
        migrations.AlterModelTable(
            name="salesstatistics",
            table="OilNote_StationApp_salesstatistics",
        ),
        migrations.AlterModelTable(
            name="stationcardmapping",
            table="OilNote_StationApp_stationcardmapping",
        ),
        migrations.AlterModelTable(
            name="stationcouponquota",
            table="OilNote_StationApp_stationcouponquota",
        ),
    ]
