# Generated by Django 4.2.23 on 2025-09-01 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StationBusinessInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(max_length=100, verbose_name="주유소명"),
                ),
                (
                    "representative_name",
                    models.CharField(max_length=50, verbose_name="대표자명"),
                ),
                (
                    "business_registration_number",
                    models.CharField(max_length=20, verbose_name="사업자등록번호"),
                ),
                (
                    "sub_business_number",
                    models.CharField(max_length=10, verbose_name="종사업자 번호"),
                ),
                ("business_address", models.TextField(verbose_name="사업장 주소")),
                (
                    "business_type",
                    models.CharField(max_length=100, verbose_name="업태"),
                ),
                (
                    "business_category",
                    models.CharField(max_length=100, verbose_name="종목"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="전화번호"),
                ),
                (
                    "refinery_company",
                    models.CharField(max_length=50, verbose_name="정유사"),
                ),
                (
                    "petroleum_management_code",
                    models.CharField(max_length=20, verbose_name="석유관리원 코드"),
                ),
                ("oil_code", models.CharField(max_length=50, verbose_name="유개코드")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "주유소 사업자 정보",
                "verbose_name_plural": "주유소 사업자 정보",
                "db_table": "OilNote_StationsManageApp_stationbusinessinfo",
            },
        ),
    ]
