# Generated by Django 4.2.23 on 2025-09-01 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OilNote_StationsManageApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="품목 코드"
                    ),
                ),
                ("item_name", models.CharField(max_length=100, verbose_name="품목명")),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("일반유", "일반유"),
                            ("TBA", "TBA"),
                            ("세차", "세차"),
                            ("기타", "기타"),
                        ],
                        max_length=20,
                        verbose_name="상품 분류",
                    ),
                ),
                (
                    "inventory_management",
                    models.CharField(
                        choices=[("예", "예"), ("아니오", "아니오")],
                        default="예",
                        max_length=10,
                        verbose_name="재고관리여부",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "유종 및 유외상품 정보",
                "verbose_name_plural": "유종 및 유외상품 정보",
                "db_table": "OilNote_StationsManageApp_productinfo",
                "ordering": ["item_code"],
            },
        ),
    ]
