# Generated by Django 4.2.23 on 2025-09-01 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OilNote_StationsManageApp", "0002_productinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TankInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tank_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="탱크 코드"
                    ),
                ),
                (
                    "tank_number",
                    models.CharField(max_length=10, verbose_name="탱크번호"),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("고급휘발유", "고급휘발유"),
                            ("휘발유", "휘발유"),
                            ("경유", "경유"),
                            ("등유", "등유"),
                            ("요소수", "요소수"),
                            ("LPG", "LPG"),
                            ("기타", "기타"),
                        ],
                        max_length=20,
                        verbose_name="품목(유종)명",
                    ),
                ),
                (
                    "permitted_capacity",
                    models.IntegerField(verbose_name="허가 용량(Ltr)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "탱크 정보",
                "verbose_name_plural": "탱크 정보",
                "db_table": "OilNote_StationsManageApp_tankinfo",
                "ordering": ["tank_code"],
            },
        ),
    ]
