# Generated by Django 4.2.23 on 2025-09-01 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OilNote_StationsManageApp", "0003_tankinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="NozzleInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nozzle_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="노즐 코드"
                    ),
                ),
                (
                    "nozzle_number",
                    models.CharField(max_length=10, verbose_name="노즐 번호"),
                ),
                (
                    "fuel_type",
                    models.CharField(max_length=20, verbose_name="품목(유종)명"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "connected_tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nozzles",
                        to="OilNote_StationsManageApp.tankinfo",
                        verbose_name="연결탱크번호",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "주유기 노즐 정보",
                "verbose_name_plural": "주유기 노즐 정보",
                "db_table": "OilNote_StationsManageApp_nozzleinfo",
                "ordering": ["nozzle_code"],
            },
        ),
    ]
