# Generated by Django 4.2.23 on 2025-09-01 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OilNote_StationsManageApp", "0005_homelorivehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="코드 번호"
                    ),
                ),
                (
                    "payment_type_name",
                    models.CharField(max_length=100, verbose_name="결제 형태명"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제 형태 정보",
                "verbose_name_plural": "결제 형태 정보",
                "db_table": "OilNote_StationsManageApp_paymenttype",
                "ordering": ["code_number"],
            },
        ),
    ]
