# Generated by Django 4.2.23 on 2025-09-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_StationsManageApp", "0006_paymenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="tankinfo",
            name="initial_inventory",
            field=models.IntegerField(default=0, verbose_name="기초재고량(Ltr)"),
        ),
    ]
