# Generated by Django 4.2.23 on 2025-09-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_StationsManageApp", "0007_tankinfo_initial_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="nozzleinfo",
            name="initial_meter_data",
            field=models.DecimalField(
                decimal_places=3,
                default=0.0,
                max_digits=10,
                verbose_name="기초 계기자료",
            ),
        ),
    ]
