# Generated by Django 4.2.23 on 2025-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_StationsManageApp", "0008_nozzleinfo_initial_meter_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="initial_inventory_quantity",
            field=models.IntegerField(default=0, verbose_name="기초재고수량"),
        ),
    ]
