# Generated by Django 4.2.23 on 2025-09-03 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OilNote_StationsManageApp", "0009_productinfo_initial_inventory_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationbusinessinfo",
            name="business_code",
            field=models.CharField(
                default="000000", max_length=20, unique=True, verbose_name="거래처 코드"
            ),
        ),
        migrations.AddField(
            model_name="stationbusinessinfo",
            name="business_name",
            field=models.CharField(default="", max_length=100, verbose_name="거래처명"),
        ),
        migrations.AddField(
            model_name="stationbusinessinfo",
            name="initial_balance",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="기초잔액"
            ),
        ),
        migrations.AlterField(
            model_name="stationbusinessinfo",
            name="business_registration_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="사업자등록번호"
            ),
        ),
        migrations.AlterField(
            model_name="stationbusinessinfo",
            name="representative_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="대표자명"
            ),
        ),
        migrations.AlterField(
            model_name="stationbusinessinfo",
            name="station_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="주유소명"
            ),
        ),
        migrations.AlterField(
            model_name="stationbusinessinfo",
            name="sub_business_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="종사업자 번호"
            ),
        ),
        migrations.AlterField(
            model_name="stationbusinessinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
    ]
