# Generated by Django 4.2.23 on 2025-07-13 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerVisitHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tid",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="주유소 TID"
                    ),
                ),
                ("visit_date", models.DateField(verbose_name="방문일")),
                ("visit_time", models.TimeField(verbose_name="방문시간")),
                (
                    "payment_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="결제구분"
                    ),
                ),
                (
                    "product_pack",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="제품/PACK"
                    ),
                ),
                (
                    "sale_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="판매금액",
                    ),
                ),
                (
                    "approval_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="승인번호"
                    ),
                ),
                (
                    "visit_count",
                    models.PositiveIntegerField(default=0, verbose_name="총 방문횟수"),
                ),
                (
                    "monthly_visit_count",
                    models.PositiveIntegerField(default=0, verbose_name="월 방문횟수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "CUSTOMER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="고객",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객 방문 내역",
                "verbose_name_plural": "고객 방문 내역",
                "ordering": ["-visit_date", "-visit_time"],
                "unique_together": {
                    (
                        "customer",
                        "station",
                        "visit_date",
                        "visit_time",
                        "approval_number",
                    )
                },
            },
        ),
    ]
