# Generated by Django 4.2.23 on 2025-07-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_UserApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customervisithistory",
            name="fuel_quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="주유량(L)"
            ),
        ),
    ]
