# Generated by Django 4.2.23 on 2025-07-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_UserApp", "0002_customervisithistory_fuel_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customervisithistory",
            name="monthly_visit_count",
        ),
        migrations.RemoveField(
            model_name="customervisithistory",
            name="visit_count",
        ),
    ]
