# Generated by Django 4.2.23 on 2025-07-09 14:06

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("CUSTOMER", "일반 고객"), ("STATION", "주유소")],
                        default="CUSTOMER",
                        max_length=10,
                        verbose_name="사용자 유형",
                    ),
                ),
                (
                    "pw_back",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="백업 패스워드",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="주유소명"
                    ),
                ),
                (
                    "station_address",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="주유소 주소",
                    ),
                ),
                (
                    "business_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="사업자 번호"
                    ),
                ),
                (
                    "car_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="차량 번호"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "1. 사용자들",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="StationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="사업자등록번호"
                    ),
                ),
                (
                    "station_name",
                    models.CharField(max_length=100, verbose_name="주유소명"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="주소"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "oil_company_code",
                    models.CharField(
                        default="0", max_length=1, verbose_name="정유사코드"
                    ),
                ),
                (
                    "agency_code",
                    models.CharField(
                        default="000", max_length=3, verbose_name="대리점코드"
                    ),
                ),
                (
                    "station_code",
                    models.CharField(
                        default="000000000000", max_length=12, verbose_name="주유소코드"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "주유소 프로필",
                "verbose_name_plural": "주유소 프로필",
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="이름"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "car_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="차량 번호"
                    ),
                ),
                (
                    "car_model",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="차량 모델"
                    ),
                ),
                (
                    "membership_card",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="멤버십 카드 번호",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GASOLINE", "휘발유"),
                            ("DIESEL", "경유"),
                            ("LPG", "LPG"),
                            ("ELECTRIC", "전기"),
                            ("HYBRID", "하이브리드"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="연료 타입",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "고객 프로필",
                "verbose_name_plural": "4. 고객 프로필들",
            },
        ),
        migrations.CreateModel(
            name="CustomerUser",
            fields=[],
            options={
                "verbose_name": "일반 고객",
                "verbose_name_plural": "2. 일반 고객들",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OilNote_User.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="StationUser",
            fields=[],
            options={
                "verbose_name": "주유소 고객들",
                "verbose_name_plural": "3. 주유소 고객들",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OilNote_User.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CustomerStationRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주거래 여부"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=0, verbose_name="포인트"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "CUSTOMER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_relations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="고객",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_relations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객-주유소 관계",
                "verbose_name_plural": "고객-주유소 관계",
                "unique_together": {("customer", "station")},
            },
        ),
    ]
