# Generated by Django 4.2.23 on 2025-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_User", "0002_stationprofile_tid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stationprofile",
            name="station_code",
        ),
        migrations.AlterField(
            model_name="stationprofile",
            name="tid",
            field=models.CharField(
                blank=True,
                help_text="카드 결제 단말기 번호를 입력하세요",
                max_length=20,
                null=True,
                verbose_name="단말기 번호(TID)",
            ),
        ),
    ]
