# Generated by Django 4.2.23 on 2025-07-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_User", "0004_alter_stationprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="group",
            field=models.CharField(
                blank=True,
                help_text="고객을 분류하기 위한 그룹",
                max_length=100,
                null=True,
                verbose_name="고객 그룹",
            ),
        ),
    ]
