# Generated by Django 4.2.23 on 2025-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_User", "0006_stationprofile_latitude_stationprofile_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerprofile",
            options={
                "verbose_name": "고객 프로필",
                "verbose_name_plural": "3. 고객 프로필들",
            },
        ),
        migrations.AlterModelOptions(
            name="customerstationrelation",
            options={
                "verbose_name": "고객-주유소 관계",
                "verbose_name_plural": "5. 고객-주유소 관계",
            },
        ),
        migrations.AlterModelOptions(
            name="customeruser",
            options={
                "verbose_name": "일반 고객",
                "verbose_name_plural": "1. 일반 고객들",
            },
        ),
        migrations.AlterModelOptions(
            name="stationprofile",
            options={
                "verbose_name": "주유소 프로필",
                "verbose_name_plural": "4. 주유소 프로필들",
            },
        ),
        migrations.AlterModelOptions(
            name="stationuser",
            options={
                "verbose_name": "주유소 고객들",
                "verbose_name_plural": "2. 주유소 고객들",
            },
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="last_fuel_cost",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="최근 주유금액(원)",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="monthly_fuel_cost",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="월 주유금액(원)",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="total_fuel_cost",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="총 주유금액(원)",
            ),
        ),
    ]
