# Generated by Django 4.2.23 on 2025-08-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_User", "0007_alter_customerprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customerprofile",
            table="Cust_User_customerprofile",
        ),
        migrations.AlterModelTable(
            name="customerstationrelation",
            table="Cust_User_customerstationrelation",
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="Cust_User_customuser",
        ),
        migrations.AlterModelTable(
            name="stationprofile",
            table="Cust_User_stationprofile",
        ),
    ]
