# Generated by Django 4.2.23 on 2025-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_User", "0008_alter_customerprofile_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stations_manage",
            field=models.BooleanField(
                default=False, verbose_name="주유소 관리 시스템 사용"
            ),
        ),
    ]
