# Generated by Django 4.2.23 on 2025-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_User", "0009_customuser_stations_manage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stations_crm",
            field=models.BooleanField(
                default=False, verbose_name="주유소 CRM 시스템 사용"
            ),
        ),
    ]
