# Generated by Django 4.2.7 on 2025-07-03 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PointCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="카드번호"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="사용 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="등록일"
                    ),
                ),
            ],
            options={
                "verbose_name": "포인트카드",
                "verbose_name_plural": "포인트카드",
                "ordering": ["-created_at"],
            },
        ),
    ]
