# Generated by Django 4.2.23 on 2025-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_StationApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pointcard",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "멤버십 카드",
                "verbose_name_plural": "멤버십 카드 목록",
            },
        ),
        migrations.AlterField(
            model_name="pointcard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="카드 생성일시"),
        ),
        migrations.AlterField(
            model_name="pointcard",
            name="is_used",
            field=models.BooleanField(default=False, help_text="카드 사용 여부"),
        ),
        migrations.AlterField(
            model_name="pointcard",
            name="number",
            field=models.CharField(
                help_text="16자리 카드번호", max_length=16, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="pointcard",
            name="tids",
            field=models.JSONField(default=list, help_text="카드가 등록된 TID 목록"),
        ),
        migrations.AlterField(
            model_name="pointcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="카드 수정일시"),
        ),
    ]
