# Generated by Django 4.2.7 on 2025-07-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_StationApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
    ]
