# Generated by Django 4.2.7 on 2025-07-04 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Cust_StationApp", "0002_pointcard_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationCardMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="등록일"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Cust_StationApp.pointcard",
                        verbose_name="포인트카드",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "주유소-카드 매핑",
                "verbose_name_plural": "주유소-카드 매핑",
                "ordering": ["-registered_at"],
                "unique_together": {("station", "card")},
            },
        ),
        migrations.AddField(
            model_name="pointcard",
            name="stations",
            field=models.ManyToManyField(
                limit_choices_to={"user_type": "STATION"},
                related_name="registered_cards",
                through="Cust_StationApp.StationCardMapping",
                to=settings.AUTH_USER_MODEL,
                verbose_name="등록 주유소",
            ),
        ),
    ]
