# Generated by Django 4.2.7 on 2025-07-04 03:04

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0010_remove_customuser_point_card_number"),
        ("Cust_StationApp", "0004_migrate_existing_cards"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationList",
            fields=[],
            options={
                "verbose_name": "주유소",
                "verbose_name_plural": "주유소 목록",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Cust_User.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
