# Generated by Django 4.2.23 on 2025-07-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_User", "0016_alter_customerprofile_bonus_card_and_more"),
        ("Cust_StationApp", "0005_stationlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="포인트 변경")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("적립", "적립"),
                            ("사용", "사용"),
                            ("수정", "수정"),
                            ("차감", "차감"),
                        ],
                        max_length=10,
                        verbose_name="변경 유형",
                    ),
                ),
                ("reason", models.CharField(max_length=200, verbose_name="변경 사유")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "customer_station_relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_history",
                        to="Cust_User.customerstationrelation",
                        verbose_name="고객-주유소 관계",
                    ),
                ),
            ],
            options={
                "verbose_name": "포인트 내역",
                "verbose_name_plural": "포인트 내역",
                "ordering": ["-created_at"],
            },
        ),
    ]
