# Generated by Django 4.2.23 on 2025-07-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_StationApp", "0006_excelsalesdata_tid"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tid",
                    models.CharField(
                        max_length=20,
                        verbose_name="TID",
                    ),
                ),
                ("sale_date", models.DateField(verbose_name="판매일자")),
                (
                    "total_transactions",
                    models.IntegerField(default=0, verbose_name="총 거래건수"),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="총 판매수량",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="총 판매금액",
                    ),
                ),
                (
                    "avg_unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="평균 단가",
                    ),
                ),
                (
                    "top_product",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="최다 판매 제품",
                    ),
                ),
                (
                    "top_product_count",
                    models.IntegerField(default=0, verbose_name="최다 판매 제품 수량"),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="원본파일명"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "매출 통계",
                "verbose_name_plural": "매출 통계 목록",
                "ordering": ["-sale_date", "-created_at"],
                "unique_together": {("tid", "sale_date", "source_file")},
            },
        ),
    ]
