# Generated by Django 4.2.23 on 2025-07-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_StationApp", "0009_monthlysalesstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlysalesstatistics",
            name="product_sales_amount",
            field=models.JSONField(default=dict, verbose_name="제품별 판매금액"),
        ),
        migrations.AddField(
            model_name="monthlysalesstatistics",
            name="product_sales_count",
            field=models.JSONField(default=dict, verbose_name="제품별 판매횟수"),
        ),
        migrations.AddField(
            model_name="monthlysalesstatistics",
            name="product_sales_quantity",
            field=models.JSONField(default=dict, verbose_name="제품별 판매수량"),
        ),
    ]
