# Generated by Django 4.2.23 on 2025-07-15 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "Cust_StationApp",
            "0010_monthlysalesstatistics_product_sales_amount_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="고객 그룹 이름",
                        max_length=100,
                        verbose_name="그룹명",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "station",
                    models.ForeignKey(
                        help_text="그룹을 생성한 주유소",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객 그룹",
                "verbose_name_plural": "0. 고객 그룹 목록",
                "ordering": ["-created_at"],
                "unique_together": {("name", "station")},
            },
        ),
    ]
