# Generated by Django 4.2.23 on 2025-07-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_StationApp", "0012_phonecardmapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="excelsalesdata",
            options={
                "ordering": ["-sale_date", "-sale_time"],
                "verbose_name": "엑셀 매출 데이터",
                "verbose_name_plural": "4. 엑셀 매출 데이터 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="monthlysalesstatistics",
            options={
                "ordering": ["-year_month"],
                "verbose_name": "월별 매출 통계",
                "verbose_name_plural": "5. 월별 매출 통계 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="phonecardmapping",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "폰번호-카드 연동",
                "verbose_name_plural": "6. 폰번호-카드 연동 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="salesstatistics",
            options={
                "ordering": ["-sale_date", "-created_at"],
                "verbose_name": "매출 통계",
                "verbose_name_plural": "3. 매출 통계 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="stationcardmapping",
            options={
                "ordering": ["-registered_at"],
                "verbose_name": "주유소-카드 매핑",
                "verbose_name_plural": "7. 주유소-카드 매핑",
            },
        ),
        migrations.AlterUniqueTogether(
            name="phonecardmapping",
            unique_together=set(),
        ),
    ]
