# Generated by Django 4.2.23 on 2025-07-21 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Cust_StationApp", "0013_alter_excelsalesdata_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_number",
                    models.CharField(
                        help_text="16자리 쿠폰번호",
                        max_length=16,
                        unique=True,
                        verbose_name="쿠폰번호",
                    ),
                ),
                (
                    "tid",
                    models.CharField(
                        blank=True,
                        help_text="쿠폰을 발행한 주유소 TID",
                        max_length=50,
                        null=True,
                        verbose_name="주유소 TID",
                    ),
                ),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("CAR_WASH", "세차"),
                            ("PRODUCT", "상품"),
                            ("FUEL", "주유"),
                        ],
                        help_text="쿠폰의 종류 (세차, 상품, 주유)",
                        max_length=10,
                        verbose_name="쿠폰 종류",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="쿠폰이 사용되었는지 여부",
                        verbose_name="쿠폰 사용 여부",
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        help_text="쿠폰을 소유한 고객의 전화번호",
                        max_length=15,
                        null=True,
                        verbose_name="소유 고객 전화번호",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="쿠폰이 생성된 날짜와 시간",
                        verbose_name="쿠폰 생성일자",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="쿠폰이 고객에게 발행된 날짜와 시간",
                        null=True,
                        verbose_name="쿠폰 발행일자",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="쿠폰이 사용된 날짜와 시간",
                        null=True,
                        verbose_name="쿠폰 사용일자",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        help_text="쿠폰을 발행한 주유소",
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="발행 주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "쿠폰",
                "verbose_name_plural": "8. 쿠폰 목록",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["coupon_number"], name="Cust_Statio_coupon__9bd0af_idx"
                    ),
                    models.Index(
                        fields=["customer_phone"], name="Cust_Statio_custome_d96554_idx"
                    ),
                    models.Index(
                        fields=["coupon_type"], name="Cust_Statio_coupon__a01e3a_idx"
                    ),
                    models.Index(
                        fields=["is_used"], name="Cust_Statio_is_used_85ee6e_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="Cust_Statio_created_1b705d_idx"
                    ),
                ],
            },
        ),
    ]
