# Generated by Django 4.2.23 on 2025-07-24 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Cust_StationApp", "0017_phonecardmapping_car_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationCouponQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_quota",
                    models.IntegerField(default=0, verbose_name="총 쿠폰 수량"),
                ),
                (
                    "used_quota",
                    models.IntegerField(default=0, verbose_name="사용된 수량"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "station",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_quota",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "주유소 쿠폰 수량",
                "verbose_name_plural": "11. 주유소 쿠폰 수량 관리",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerVisitHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField(verbose_name="방문일시")),
                (
                    "fuel_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="주유량",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="결제 금액",
                    ),
                ),
                ("products", models.JSONField(default=list, verbose_name="구매 상품")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "CUSTOMER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_history_as_customer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="고객",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_history_as_station",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객 방문 기록",
                "verbose_name_plural": "14. 고객 방문 기록",
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="CouponPurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_quantity", models.IntegerField(verbose_name="요청 수량")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "거부"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청일시"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="처리일시"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="비고")),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_coupon_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="처리자",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "쿠폰 구매 요청",
                "verbose_name_plural": "13. 쿠폰 구매 요청 목록",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="CumulativeSalesTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cumulative_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="누적 매출액",
                    ),
                ),
                (
                    "threshold_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=50000,
                        max_digits=10,
                        verbose_name="쿠폰 발행 임계값",
                    ),
                ),
                (
                    "last_coupon_issued_at",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="마지막 쿠폰 발행 시점의 누적액",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "CUSTOMER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cumulative_sales_as_customer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="고객",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cumulative_sales_as_station",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "누적매출 추적",
                "verbose_name_plural": "12. 누적매출 추적 목록",
                "ordering": ["-updated_at"],
                "unique_together": {("customer", "station")},
            },
        ),
    ]
