# Generated by Django 4.2.23 on 2025-07-24 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Cust_StationApp", "0018_stationcouponquota_customervisithistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoCouponTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("SIGNUP", "회원가입"),
                            ("CUMULATIVE", "누적매출"),
                            ("MONTHLY", "전월매출"),
                        ],
                        max_length=20,
                        verbose_name="쿠폰 유형",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        help_text="관리자가 식별하기 위한 템플릿 이름",
                        max_length=100,
                        verbose_name="템플릿명",
                    ),
                ),
                (
                    "coupon_name",
                    models.CharField(
                        help_text="고객에게 표시될 쿠폰 이름",
                        max_length=100,
                        verbose_name="쿠폰명",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="쿠폰에 대한 상세 설명",
                        verbose_name="설명",
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("DISCOUNT", "할인"),
                            ("PRODUCT", "상품"),
                            ("BOTH", "할인+상품"),
                        ],
                        max_length=10,
                        verbose_name="혜택 유형",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="할인 금액",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, verbose_name="상품명"),
                ),
                (
                    "condition_data",
                    models.JSONField(
                        default=dict,
                        help_text="발행 조건들을 JSON으로 저장",
                        verbose_name="조건 데이터",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="높을수록 우선 (같은 타입 내에서)",
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "max_issue_count",
                    models.IntegerField(
                        blank=True,
                        help_text="최대 발행 가능 개수 (NULL=무제한)",
                        null=True,
                        verbose_name="발행 한도",
                    ),
                ),
                (
                    "issued_count",
                    models.IntegerField(default=0, verbose_name="현재 발행수"),
                ),
                (
                    "is_permanent",
                    models.BooleanField(default=False, verbose_name="무기한 여부"),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="사용 시작일"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="사용 종료일"),
                ),
                (
                    "total_issued",
                    models.IntegerField(default=0, verbose_name="총 발행수"),
                ),
                (
                    "total_used",
                    models.IntegerField(default=0, verbose_name="총 사용수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_auto_coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "STATION"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주유소",
                    ),
                ),
            ],
            options={
                "verbose_name": "자동 쿠폰 템플릿",
                "verbose_name_plural": "15. 자동 쿠폰 템플릿 목록",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutoCouponCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("THRESHOLD_AMOUNT", "금액 임계값"),
                            ("TIME_PERIOD", "기간 조건"),
                            ("CUSTOMER_TYPE", "고객 유형"),
                            ("EXCLUDE_PREVIOUS", "기존 수령자 제외"),
                            ("VISIT_COUNT", "방문 횟수"),
                            ("FIRST_TIME_ONLY", "최초 1회만"),
                            ("WEEKDAY_ONLY", "평일만"),
                            ("WEEKEND_ONLY", "주말만"),
                            ("CUSTOMER_GRADE", "고객 등급"),
                        ],
                        max_length=20,
                        verbose_name="조건 유형",
                    ),
                ),
                (
                    "condition_value",
                    models.JSONField(
                        help_text="조건별 설정값을 JSON으로 저장",
                        verbose_name="조건 값",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="조건 설명"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="Cust_StationApp.autocoupontemplate",
                        verbose_name="자동 쿠폰 템플릿",
                    ),
                ),
            ],
            options={
                "verbose_name": "자동 쿠폰 조건",
                "verbose_name_plural": "16. 자동 쿠폰 조건 목록",
                "ordering": ["condition_type", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="autocoupontemplate",
            index=models.Index(
                fields=["station", "coupon_type", "is_active"],
                name="Cust_Statio_station_f477f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="autocoupontemplate",
            index=models.Index(
                fields=["priority"], name="Cust_Statio_priorit_554c66_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="autocoupontemplate",
            unique_together={("station", "template_name")},
        ),
    ]
