# Generated by Django 4.2.23 on 2025-07-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_StationApp", "0019_autocoupontemplate_autocouponcondition_and_more"),
    ]

    operations = [
        # Remove fields
        migrations.RemoveField(
            model_name='autocoupontemplate',
            name='template_name',
        ),
        migrations.RemoveField(
            model_name='autocoupontemplate',
            name='priority',
        ),
        # Update benefit_type choices
        migrations.AlterField(
            model_name='autocoupontemplate',
            name='benefit_type',
            field=models.CharField(
                choices=[('DISCOUNT', '할인'), ('PRODUCT', '상품')], 
                max_length=10, 
                verbose_name='혜택 유형'
            ),
        ),
    ]
