# Generated by Django 4.2.23 on 2025-07-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cust_StationApp", "0022_auto_20250724_1521"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autocoupontemplate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "자동 쿠폰 템플릿",
                "verbose_name_plural": "15. 자동 쿠폰 템플릿 목록",
            },
        ),
        migrations.AddField(
            model_name="customercoupon",
            name="auto_coupon_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Cust_StationApp.autocoupontemplate",
                verbose_name="자동 쿠폰 템플릿",
            ),
        ),
        migrations.AlterField(
            model_name="customercoupon",
            name="coupon_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Cust_StationApp.coupontemplate",
                verbose_name="쿠폰 템플릿",
            ),
        ),
        migrations.AddIndex(
            model_name="customercoupon",
            index=models.Index(
                fields=["auto_coupon_template"], name="Cust_Statio_auto_co_180c3b_idx"
            ),
        ),
    ]
