# Generated by Django for AutoCouponTemplate max_issue_count field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cust_StationApp', '0028_add_is_cumulative_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocoupontemplate',
            name='max_issue_count',
            field=models.IntegerField(blank=True, help_text='null이면 무제한 발행', null=True, verbose_name='최대 발행수'),
        ),
    ]