# Generated by Django 4.2.23 on 2025-07-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "OilNote_UserApp",
            "0003_remove_customervisithistory_monthly_visit_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customervisithistory",
            name="membership_card",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="멤버십 카드번호"
            ),
        ),
    ]
