# Generated by Django 4.2.23 on 2025-08-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_UserApp", "0004_customervisithistory_membership_card"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customervisithistory",
            table="Cust_UserApp_customervisithistory",
        ),
    ]
