# Generated by Django 4.2.23 on 2025-07-15 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FTPServerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="설정명")),
                ("host", models.CharField(max_length=255, verbose_name="FTP 호스트")),
                ("port", models.IntegerField(default=21, verbose_name="포트")),
                ("username", models.CharField(max_length=100, verbose_name="사용자명")),
                ("password", models.CharField(max_length=255, verbose_name="비밀번호")),
                (
                    "remote_path",
                    models.CharField(
                        default="/", max_length=500, verbose_name="원격 경로"
                    ),
                ),
                (
                    "local_path",
                    models.CharField(max_length=500, verbose_name="로컬 저장 경로"),
                ),
                (
                    "file_pattern",
                    models.CharField(
                        default="*.xlsx", max_length=200, verbose_name="파일 패턴"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "FTP 서버 설정",
                "verbose_name_plural": "FTP 서버 설정",
            },
        ),
        migrations.CreateModel(
            name="FTPDataSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="스케줄명")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("hourly", "매시간"),
                            ("daily", "매일"),
                            ("weekly", "매주"),
                            ("monthly", "매월"),
                            ("custom", "사용자 정의"),
                        ],
                        max_length=20,
                        verbose_name="스케줄 타입",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Cron 표현식",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 실행"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="다음 실행"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "server_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ftp_data_loader.ftpserverconfig",
                        verbose_name="FTP 설정",
                    ),
                ),
            ],
            options={
                "verbose_name": "FTP 데이터 스케줄",
                "verbose_name_plural": "FTP 데이터 스케줄",
            },
        ),
        migrations.CreateModel(
            name="FTPDataLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="파일명")),
                (
                    "remote_path",
                    models.CharField(max_length=500, verbose_name="원격 경로"),
                ),
                (
                    "local_path",
                    models.CharField(max_length=500, verbose_name="로컬 경로"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="파일 크기"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("downloading", "다운로드 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                            ("processing", "처리 중"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="오류 메시지"),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="다운로드 완료일"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="처리 완료일"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "server_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ftp_data_loader.ftpserverconfig",
                        verbose_name="FTP 설정",
                    ),
                ),
            ],
            options={
                "verbose_name": "FTP 데이터 로그",
                "verbose_name_plural": "FTP 데이터 로그",
                "ordering": ["-created_at"],
            },
        ),
    ]
