# Generated by Django 4.2.23 on 2025-07-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExcelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("phone", models.CharField(max_length=20, verbose_name="전화번호")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("address", models.CharField(max_length=200, verbose_name="주소")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
            options={
                "verbose_name": "엑셀 데이터",
                "verbose_name_plural": "엑셀 데이터 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateField(verbose_name="판매일자")),
                ("sale_time", models.TimeField(verbose_name="주유시간")),
                (
                    "payment_type",
                    models.CharField(max_length=20, verbose_name="결제구분"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=20, verbose_name="제품코드"),
                ),
                (
                    "product_pack",
                    models.CharField(max_length=50, verbose_name="제품/PACK"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="판매수량"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="판매단가"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="판매금액"
                    ),
                ),
                (
                    "approval_number",
                    models.CharField(max_length=50, verbose_name="승인번호"),
                ),
                ("approval_datetime", models.DateTimeField(verbose_name="승인일시")),
                (
                    "bonus_card",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="보너스카드"
                    ),
                ),
                (
                    "customer_card_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="고객카드번호",
                    ),
                ),
                (
                    "data_created_at",
                    models.DateTimeField(verbose_name="데이터생성일시"),
                ),
            ],
            options={
                "verbose_name": "판매 데이터",
                "verbose_name_plural": "판매 데이터",
            },
        ),
    ]
