# Generated by Django 4.2.23 on 2025-07-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel_sample", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesdata",
            name="blank_column",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="공백"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="bonus",
            field=models.IntegerField(default=0, verbose_name="보너스"),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="고객명"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="customer_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="고객번호"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="earned_points",
            field=models.IntegerField(default=0, verbose_name="적립포인트"),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="issue_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="발행번호"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="nozzle",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="노즐"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="points",
            field=models.IntegerField(default=0, verbose_name="포인트"),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="pos_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="POS코드"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="pos_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="POS_ID"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="product_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="주류상품종류"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="receipt",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="영수증"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="sale_type",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="판매구분"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="sale_type2",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="판매구분2"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="store",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="판매점"
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="approval_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="승인일시"),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="approval_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="승인번호"
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="data_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="데이터생성일시"
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="payment_type",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="결제구분"
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="product_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="제품코드"
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="product_pack",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="제품/PACK"
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="판매수량"
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="판매금액"
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="판매단가"
            ),
        ),
    ]
