# Generated by Django 4.2.23 on 2025-09-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OilNote_AdminApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminaction",
            name="admin_user",
        ),
        migrations.RemoveField(
            model_name="databackup",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="maintenanceschedule",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="SystemConfig",
        ),
        migrations.RemoveField(
            model_name="systemlog",
            name="user",
        ),
        migrations.DeleteModel(
            name="AdminAction",
        ),
        migrations.DeleteModel(
            name="DataBackup",
        ),
        migrations.DeleteModel(
            name="MaintenanceSchedule",
        ),
        migrations.DeleteModel(
            name="SystemLog",
        ),
    ]
